sudo: false
language: ruby
jdk: openjdk8
rvm:
  - 2.3.0
  - jruby-9.1.7.0
before_install:
  - gem install bundler
  - gem update --system
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.3.0/gnatsd-v1.3.0-linux-amd64.zip
  - unzip gnatsd-v1.3.0-linux-amd64.zip
  - ./gnatsd-v1.3.0-linux-amd64/gnatsd &
