sudo: false
language: ruby
jdk:
 - openjdk8
rvm:
  - 2.3.0
  - 2.7.0
  - jruby-9.1.7.0
  - jruby-9.2.13.0
before_install:
  # Install and start gnatsd
  - ./scripts/install_gnatsd.sh
  - $HOME/nats-server/nats-server &
  # Install deps for project
  - gem install bundler
  - gem update --system
